"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal 
and D = |Pk − Pj| is minimised; what is the value of D?
"""
from helpers import analytics
analytics.monitor()

def pent(n):
    return n*(3*n-1)//2

def isPent(t):
    a = (1+((1+24*t)**0.5))/6
    if a == int(a):
        return True
    return False

def main():
    pents = list(map(pent,range(1,int(1e4))))
    for i in pents:
        for j in pents:
            add = i + j
            sub = abs(i-j)
            if isPent(add) and isPent(sub):
                return sub

print(main(), analytics.lap(), analytics.maxMem())
"""
5482660 
time: 6.734127691 
max memory: 9.1MB
"""